#!/bin/sh

':' //; exec "$(command -v nodejs || command -v node)" "$0" "$@"

let mongoose = require("mongoose");
let fq = require("fuzzquire");
let config = require("../config");
let async = require("async");

let adminsModel = fq("schemas/admins");
let coursesModel = fq("schemas/courses");

mongoose.connect(
  config.mongooseConnection,
  {}
);

mongoose.connection.on("open", function(ref) {
  console.log("Please wait. This may take some time...");
  coursesModel.find({}, (err, courses) => {
    if (err) {
      console.log(err);
      process.exit();
    }
    async.eachSeries(
      courses,
      (course, nextCourse) => {
        async.eachSeries(
          course.sections,
          (section, nextSection) => {
            async.eachSeries(
              section.instructors,
              (instructor, nextInstructor) => {
                adminsModel.find({ email: instructor }, (err, result) => {
                  if (err) {
                    console.log(err);
                    process.exit();
                  }
                  if (result.length == 0) {
                    console.log(
                      `ERROR: Could not find instructor ${instructor} for ${
                        course.courseID
                      } - ${section.section}`
                    );
                  }
                  nextInstructor();
                });
              },
              () => {
                nextSection();
              }
            );
          },
          () => {
            nextCourse();
          }
        );
      },
      () => {
        console.log("Finished");
        process.exit();
      }
    );
  });
});
