#!/bin/sh

':' //; exec "$(command -v nodejs || command -v node)" "$0" "$@"

var mongoose = require('mongoose');
var portalsModel = require('../schemas/portals');
var adminsModel = require('../schemas/admins');
var divisionsModel = require('../schemas/divisions');
var config = require('../config');

mongoose.connect(config.mongooseConnection, {
	useMongoClient: true
});

portalsModel.remove({}, function (err) {

	if (err) {
		console.log(err);
	}
	console.log("Creating Portals ...");
	portalsModel.create({
			displayName: "24x7 Feedbacks",
			name: "feedbacks-24x7",
			icon: "feedback",
			active: true,
			admin: false
		}, {
			displayName: "Room Booking",
			name: "room-booking-student",
			icon: "class",
			active: true,
			admin: false
		}, {
			displayName: "Room Booking Approval",
			name: "room-booking-approval",
			icon: "done",
			active: true,
			admin: true
		}, {
			displayName: "Room Booking",
			name: "room-booking-faculty",
			icon: "class",
			active: true,
			admin: true
		}, {
			displayName: "Apply Teacher Assistantship",
			name: "ta-application",
			icon: "supervisor_account",
			active: true,
			admin: false
		},
		function (err) {

			if (err) {
				console.log(err);
			}

			console.log("Adding Superusers ...");

			adminsModel.remove({}, function (err) {

				if (err) {
					console.log(err);
				}

				adminsModel.create({
					name: "Sohail Rajdev",
					email: "sohailrajdev97@gmail.com",
					portals: [],
					home: '',
					superUser: true
				}, {
					name: "Nischay Ram Mamidi",
					email: "nischaymamidi@gmail.com",
					portals: [],
					home: '',
					superUser: true
				}, function (err) {

					if (err) {
						console.log(err);
					}

					divisionsModel.remove({}, function (err) {

						if (err) {
							console.log(err);
						}
						console.log("Creating Divisions ...");
						divisionsModel.create({
								name: "Instruction Division",
								email: "sohailrajdev97@gmail.com"
							}, {
								name: "Student Welfare Division",
								email: "rajdevsohail007@gmail.com"
							}, {
								name: "ARCD",
								email: "f20160158@hyderabad.bits-pilani.ac.in"
							},
							function (err) {
								if (err) {
									console.log(err);
								}
								console.log("**** DONE ****");
								process.exit();
							});
					});
				});
			});
		});
});
